name: build

on:
  push:
    branches: "**"
    tags: "v*.*.*"
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        run: >
          mingw32-make.exe distribution
          BEATRICE_DEV_VERSION=${{ startsWith(github.ref, 'refs/tags/v') && 'OFF' || 'ON' }}

      - name: Upload VST
        uses: actions/upload-artifact@v7
        with:
          name: beatrice
          path: |
            ${{github.workspace}}/build/vst/beatrice_*/
            !${{github.workspace}}/build/vst/beatrice_*.dir
